// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCle6Q0II3LrcxWzJAxKFKte53MpZdW_q8',
    appId: '1:936460764842:android:cbe302eb29d502e0eeb2d3',
    messagingSenderId: '936460764842',
    projectId: 'delivery-sopetran',
    databaseURL: 'https://delivery-sopetran-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-sopetran.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkTqH2Dqq4rc-kFeX3J4C4e2YmorQjfAg',
    appId: '1:936460764842:ios:858f21d48c98d6f0eeb2d3',
    messagingSenderId: '936460764842',
    projectId: 'delivery-sopetran',
    databaseURL: 'https://delivery-sopetran-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-sopetran.appspot.com',
    androidClientId: '936460764842-suatjarldno71rtvonr2vf2fmgip3r52.apps.googleusercontent.com',
    iosClientId: '936460764842-2374s3cmimvuouqp1sksanotiu1l5u6b.apps.googleusercontent.com',
    iosBundleId: 'com.rockstone.sopefoodusuario',
  );
}
